### PR TITLE
Fix update

### PR DESCRIPTION
**Pull request by jreidinger**
related to https://github.com/yast/yast-installation/pull/923

### CODE REVIEW

**Review by dgdavid — APPROVED** [review]
LGTM, thanks for the fix

**Review by dgdavid — CHANGES_REQUESTED** [review]
But, wait. Should we fix it in SP2 first?

**Comment by jreidinger** [comment]
@dgdavid in SLE15 SP2 it is driven by firewall finish which is not called in upgrade - https://github.com/yast/yast-firewall/blob/SLE-15-SP2/src/lib/y2firewall/clients/installation_finish.rb#L54

**Comment by dgdavid** [comment]
> @dgdavid in SLE15 SP2 it is driven by firewall finish which is not called in upgrade - https://github.com/yast/yast-firewall/blob/SLE-15-SP2/src/lib/y2firewall/clients/installation_finish.rb#L54

Ok, but look like those changes could be applied safely in SP2 too, or am I wrong?

**Comment by dgdavid** [comment]
Closed in favor of #100

**Pull request closed without merging**
